# Generated by Django 5.1.1 on 2024-09-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prouducts_test',
            field=models.ManyToManyField(to='shop.product'),
        ),
    ]
